spring:
    profiles:
        active:
            - dev
        
---
server:
  port: 8001

spring:
  profiles: dev #生产环境
  application:
    name: microservice-cloud-provider
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/database01?serverTimeZone=UTC
    driver-class-name: org.gjt.mm.mysql.Driver
mybatis:
  config-location: classpath:mybatis/mybatis-cfg.xml
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml
  type-aliases-package: com.lrh.cloud.api.bean
eureka:
  instance:
    prefer-ip-address: true   #访问地址可以显示ip地址
    instance-id: microservice-cloud-provider8001
  client:
    service-url:
#    单机  defaultZone: http://localhost:7001/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      
---
server:
  port: 8001

spring:
  profiles: test
  application:
    name: microservice-cloud-provider
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/database02?serverTimeZone=UTC
    driver-class-name: org.gjt.mm.mysql.Driver
mybatis:
  config-location: classpath:mybatis/mybatis-cfg.xml
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml
  type-aliases-package: com.lrh.cloud.api.bean
eureka:
  instance:
    prefer-ip-address: true   #访问地址可以显示ip地址
    instance-id: microservice-cloud-provider8001
  client:
    service-url:
#    单机  defaultZone: http://localhost:7001/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/      